name: moon-generator

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu çek
        uses: actions/checkout@v4 # v3 yerine v4

      - name: Python kurulumu
        uses: actions/setup-python@v5 # v4 yerine v5
        with:
          python-version: '3.9'

      - name: Gerekli kütüphaneleri kur
        run: pip install requests

      - name: Scripti çalıştır
        run: python converter.py

      - name: Sonuçları kaydet
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add m3u_cikti/*
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik M3U güncellemesi" && git push)
