name: moon-generator

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

# GitHub Actions'ın dosyaları yazabilmesi için gerekli izin
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu çek
        uses: actions/checkout@v3

      - name: Python kurulumu
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Gerekli kütüphaneleri kur
        run: pip install requests

      - name: Scripti çalıştır
        run: python converter.py

      - name: Sonuçları kaydet (Commit & Push)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # m3u_cikti klasöründeki tüm dosyaları ekle
          git add m3u_cikti/*
          
          # Eğer değişiklik varsa commit at, yoksa hata vermeden çık
          git diff --quiet && git diff --staged --quiet || (git commit -m "Otomatik M3U güncellemesi" && git push)
